# Generated by Django 4.2.7 on 2024-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('receipt_number', models.CharField(max_length=12, unique=True)),
                ('date_of_payment', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_of_payment', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_details', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UniquePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('date_of_payment', models.DateField()),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
