# Generated by Django 4.2.7 on 2024-09-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-is_current', '-version'], 'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.AddField(
            model_name='resume',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any additional information relevant to the resume', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='awards',
            field=models.TextField(blank=True, help_text='List of awards and achievements', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='educations',
            field=models.TextField(blank=True, help_text='List of educational qualifications', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='interests',
            field=models.TextField(blank=True, help_text='List of interests and hobbies', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='memberships',
            field=models.TextField(blank=True, help_text='List of professional memberships', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True, help_text='List of significant projects', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='publications',
            field=models.TextField(blank=True, help_text='List of publications', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='references',
            field=models.TextField(blank=True, help_text='List of professional references', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='soft_skills',
            field=models.TextField(blank=True, help_text='List of soft skills', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='technical_skills',
            field=models.TextField(blank=True, help_text='List of technical skills', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resume',
            name='volunteer_experiences',
            field=models.TextField(blank=True, help_text='List of volunteer experiences', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experiences',
            field=models.TextField(blank=True, help_text='List of work experiences', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='class_schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='partnership',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='target_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='studentpage.candidate'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True, help_text='List of certifications', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='languages',
            field=models.TextField(blank=True, help_text='List of languages and proficiency levels', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, help_text='A brief personal statement or career objective', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='resume',
            unique_together={('candidate', 'version')},
        ),
        migrations.RemoveField(
            model_name='resume',
            name='company',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education_tenure',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='reference_companies',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='reference_contacts',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='reference_names',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='role',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='school',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_tenure',
        ),
    ]
