# Generated by Django 4.2.7 on 2024-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=255)),
                ('starting_month', models.DateField()),
                ('due_date', models.DateField()),
                ('custom_due_date', models.DateField(blank=True, null=True)),
                ('total_amount_to_pay', models.IntegerField()),
                ('invoice_number', models.CharField(max_length=12)),
                ('has_gap_period', models.BooleanField(default=False)),
                ('gap_period_start_date', models.DateField(blank=True, null=True)),
                ('fee_instance', models.CharField(max_length=255, null=True)),
                ('is_first_month', models.BooleanField(default=False)),
                ('entry_order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
