# Generated by Django 4.2.7 on 2024-09-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Date_of_Admission', models.DateField()),
                ('German_Level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2')], default='None', max_length=50, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='admissions/')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_contract', models.FileField(blank=True, null=True, upload_to='students_contracts/')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='studentpage.candidate')),
            ],
        ),
    ]
