# Generated by Django 4.2.7 on 2024-09-10 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_intake', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_password_change', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'Other')], default='None', max_length=50, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('nationality', models.CharField(blank=True, choices=[('Kenyan', 'Kenyan'), ('Other', 'Other')], max_length=45, null=True)),
                ('religion', models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Christian', 'Christian'), ('Other', 'Other')], max_length=45, null=True)),
                ('course_location', models.CharField(blank=True, choices=[('Nairobi_CBD', 'Nairobi_CBD'), ('Nairobi_Hospital', 'Nairobi_Hospital'), ('Nairobi_Karen', 'Nairobi_Karen'), ('Nairobi_Daystar', 'Nairobi_Daystar'), ('Mombasa', 'Mombasa'), ('Muranga', 'Muranga'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Eldoret', 'Eldoret'), ('Thika', 'Thika')], max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_class_no', models.CharField(max_length=255)),
                ('is_pinned', models.BooleanField(default=False)),
                ('course_intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherpage.courseintake')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherpage.teacher')),
            ],
        ),
    ]
