# Generated by Django 4.2.7 on 2024-09-10 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentpage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField()),
                ('absent_reason', models.CharField(blank=True, choices=[('Too Late', 'Too Late'), ('Absent with Excuse', 'Absent with Excuse'), ('Absent without Excuse', 'Absent without Excuse')], max_length=255, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpage.candidate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
