# Generated by Django 4.2.7 on 2024-09-10 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentpage', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, upload_to='candidate_qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='studentpage.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='QRScannerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='qrscanner_users', related_query_name='qrscanner_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='qrscanner_users_permissions', related_query_name='qrscanner_user_permission', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(choices=[('Online', 'Online'), ('Nairobi_CBD', 'Nairobi_CBD'), ('Nairobi_Hospital', 'Nairobi_Hospital'), ('Nairobi_Karen', 'Nairobi_Karen'), ('Nairobi_Daystar', 'Nairobi_Daystar'), ('Mombasa', 'Mombasa'), ('Muranga', 'Muranga'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Eldoret', 'Eldoret'), ('Thika', 'Thika')], max_length=50, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qrcodes.candidateqrcode')),
            ],
        ),
    ]
