# Generated by Django 4.2.7 on 2024-09-10 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentpage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacherpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('class_level', models.CharField(blank=True, choices=[('A1.1', 'A1.1'), ('A1.2', 'A1.2'), ('A2.1', 'A2.1'), ('A2.2', 'A2.2'), ('B1.1', 'B1.1'), ('B1.2', 'B1.2'), ('B2.1', 'B2.1'), ('B2.2', 'B2.2'), ('Custom name', 'Custom name')], max_length=50, null=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('class_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherpage.cohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_score', models.CharField(blank=True, max_length=255, null=True)),
                ('missed_exam_reason', models.CharField(blank=True, choices=[('Sick', 'Sick'), ('Personal Reason', 'Personal Reason'), ('Missed without Excuse', 'Missed without Excuse')], max_length=255, null=True)),
                ('speaking_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('listening_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reading_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('writing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('speaking_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('listening_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reading_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('writing_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('speaking_missed_reason', models.CharField(blank=True, choices=[('Sick', 'Sick'), ('Personal Reason', 'Personal Reason'), ('Missed without Excuse', 'Missed without Excuse')], max_length=255, null=True)),
                ('listening_missed_reason', models.CharField(blank=True, choices=[('Sick', 'Sick'), ('Personal Reason', 'Personal Reason'), ('Missed without Excuse', 'Missed without Excuse')], max_length=255, null=True)),
                ('reading_missed_reason', models.CharField(blank=True, choices=[('Sick', 'Sick'), ('Personal Reason', 'Personal Reason'), ('Missed without Excuse', 'Missed without Excuse')], max_length=255, null=True)),
                ('writing_missed_reason', models.CharField(blank=True, choices=[('Sick', 'Sick'), ('Personal Reason', 'Personal Reason'), ('Missed without Excuse', 'Missed without Excuse')], max_length=255, null=True)),
                ('name_of_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpage.candidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaking_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('listening_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reading_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('writing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teachers_notes', models.TextField(blank=True)),
                ('way_forward', models.CharField(blank=True, choices=[('Defer student', 'Defer student'), ('Student stays in class', 'Student stays in class'), ('Repeat class', 'Repeat class')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('admin_decision_date', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpage.candidate')),
                ('student_exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examination_report', to='academics.studentexam')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherpage.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_dates', to='academics.examination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_exam_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'examination')},
            },
        ),
        migrations.CreateModel(
            name='ClassReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_report', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherpage.cohort')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.examination')),
            ],
            options={
                'unique_together': {('examination', 'cohort')},
            },
        ),
    ]
